stages:
  download:
    cmd: uv run python3 -m air_quality_prediction.data.download_data
    deps:
      - air_quality_prediction/data/download_data.py
    outs:
      - data/raw/air_weather_data_lite.csv:
          cache: true
          persist: false
